<?php
/**
 * Created by PhpStorm.
 * User: colin
 * Date: 2018/9/1
 * Time: 下午2:12
 */

namespace app\admin\controller;


use app\common\traits\Aide;
use think\Controller;
use think\Request;
use think\auth;

class AuthRule extends Common
{
    //定义模块变量
    protected $model = 'AuthRule';


    public function _initialize()
    {

        $this->model = $this->model?:request()->controller();

        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function test(){
        echo $this->model;
    }




}