<?php
/**
 * Created by PhpStorm.
 * User: colin
 * Date: 2018/9/1
 * Time: 下午1:19
 */

namespace app\admin\controller;


use app\common\traits\Aide;
use think\auth\Auth;
use think\Controller;
use think\Request;
use think\Response;
use think\Db;


class Common extends Controller
{
    /**
     * 定义私有变量
     * @param model => 模型名称
     * @param controller => 控制器名称
     * @param action => 操作方法名称
     * @param field => 获取数据展示字段(默认全部)
     * @param status => 状态变量
     * @param relation => 关联关系 array 可以多个
     */
    //当前操作模型名称
    protected $model = '';
    //控制器名称
    protected $controller = '';
    //操作方法名称
    protected $action = '';
    //获取展示数据字段
    protected $field = '*';
    //状态变量
    protected $status = 'status';
    //关联表名称
    protected $relation = array();


    use Aide;
    /*
     * 初始化方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //初始化模型名称，可以从继承类里覆盖
        $this->model = \request()->controller();
        //初始化控制器名称，可以从继承类里覆盖
        $this->controller = \request()->controller();
        //初始化方法名称,可以从继承类里覆盖
        $this->action = \request()->action();
        $rule = $this->controller.DS.$this->action;

        //进行权限判断
        $auth = new Auth();
        if(!$auth->check($rule,1)){
//            $this->error('没有操作权限！');
        }

        //获取当前用户的权限菜单

        //
    }



}