<?php
/**
 * Created by PhpStorm.
 * User: colin
 * Date: 2018/9/2
 * Time: 下午8:01
 */

namespace app\admin\controller;

use app\common\controller;
use app\common\traits\Aide;

class Index extends Common
{
    use Aide;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 欢迎页面
     */
    public function welcome()
    {

        //此处写获取信息代码，在主页展示
        return $this->fetch();
    }
}