<?php
/**
 * Created by PhpStorm.
 * User: colin
 * Date: 2018/9/2
 * Time: 下午5:57
 */
namespace app\admin\controller;

use think\Controller;

class Login extends Controller{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * 登陆
     */
    public function login(){

    }
    /**
     * 验证登陆
     */
    public function login_do(){

    }

    /**
     * 退出登陆
     */
    public function login_out(){

    }


}